variable "aws_region" {
  description = "AWS region for the demo stack."
  type        = string
  default     = "us-west-2"
}

variable "project_name" {
  description = "Short project name used in AWS resource names."
  type        = string
  default     = "lending-workflow"

  validation {
    condition     = can(regex("^[a-z0-9-]{3,24}$", var.project_name))
    error_message = "project_name must be 3-24 lowercase letters, numbers, or hyphens."
  }
}

variable "environment" {
  description = "Environment suffix. This stack is intentionally sized for a disposable demo."
  type        = string
  default     = "demo"

  validation {
    condition     = can(regex("^[a-z0-9-]{2,12}$", var.environment))
    error_message = "environment must be 2-12 lowercase letters, numbers, or hyphens."
  }
}

variable "vpc_cidr" {
  description = "CIDR for the VPC."
  type        = string
  default     = "10.42.0.0/16"
}

variable "availability_zones" {
  description = "Optional two-AZ override. By default Terraform selects the first two available AZs in aws_region."
  type        = list(string)
  default     = null
  nullable    = true

  validation {
    condition     = var.availability_zones == null ? true : length(var.availability_zones) == 2
    error_message = "The demo topology requires exactly two availability zones."
  }
}

variable "db_instance_class" {
  description = "Small RDS class for the synthetic demo. Increase for a real workload."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_name" {
  description = "PostgreSQL database name."
  type        = string
  default     = "lending"
}

variable "db_username" {
  description = "PostgreSQL master username. The password is generated by RDS Secrets Manager integration."
  type        = string
  default     = "lending_app"
}

variable "application_image" {
  description = "Application-service image. Defaults to the latest tag in this stack's ECR repository."
  type        = string
  default     = null
  nullable    = true
}

variable "worker_image" {
  description = "Decision-worker image. Defaults to the latest tag in this stack's ECR repository."
  type        = string
  default     = null
  nullable    = true
}

variable "application_desired_count" {
  description = "Application ECS task count for the demo."
  type        = number
  default     = 1
}

variable "worker_desired_count" {
  description = "Decision-worker ECS task count for the demo."
  type        = number
  default     = 1
}

variable "internal_api_token" {
  description = "Shared secret for the private worker-to-application callback. Pass through CI or a tfvars file outside git."
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.internal_api_token) >= 32
    error_message = "internal_api_token must contain at least 32 characters."
  }
}

variable "tags" {
  description = "Additional tags applied to all supported resources."
  type        = map(string)
  default     = {}
}
